"""RFC 8439 ChaCha20-Poly1305 test vectors.

Official IETF test vectors for ChaCha20 and Poly1305 for IETF Protocols.
Source: https://www.rfc-editor.org/rfc/rfc8439.html

Appendix A contains test vectors for:
- A.1: ChaCha20 Block Function
- A.2: ChaCha20 Encryption
- A.3: Poly1305 MAC
- A.4: Poly1305 Key Generation
- A.5: ChaCha20-Poly1305 AEAD

We focus on AEAD tests (A.5) as that's what our HPKE implementation uses.

To update: These are hardcoded from the RFC specification.
"""

import pytest
from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305


@pytest.mark.vectors
class TestRFC8439ChaCha20Poly1305:
    """RFC 8439 Appendix A test vectors."""

    def test_aead_encryption_section_2_8_2(self) -> None:
        """RFC 8439 Section 2.8.2 - Example and Test Vector for AEAD_CHACHA20_POLY1305."""
        # Test vector from Section 2.8.2
        key = bytes.fromhex("808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f")
        nonce = bytes.fromhex("070000004041424344454647")
        aad = bytes.fromhex("50515253c0c1c2c3c4c5c6c7")
        plaintext = (
            b"Ladies and Gentlemen of the class of '99: "
            b"If I could offer you only one tip for the future, sunscreen would be it."
        )

        expected_ciphertext = bytes.fromhex(
            "d31a8d34648e60db7b86afbc53ef7ec2"
            "a4aded51296e08fea9e2b5a736ee62d6"
            "3dbea45e8ca9671282fafb69da92728b"
            "1a71de0a9e060b2905d6a5b67ecd3b36"
            "92ddbd7f2d778b8c9803aee328091b58"
            "fab324e4fad675945585808b4831d7bc"
            "3ff4def08e4b7a9de576d26586cec64b"
            "6116"
        )
        expected_tag = bytes.fromhex("1ae10b594f09e26a7e902ecbd0600691")

        cipher = ChaCha20Poly1305(key)

        # Test encryption
        ciphertext_with_tag = cipher.encrypt(nonce, plaintext, aad)
        ciphertext = ciphertext_with_tag[:-16]
        tag = ciphertext_with_tag[-16:]

        assert ciphertext == expected_ciphertext, "Ciphertext mismatch"
        assert tag == expected_tag, "Tag mismatch"

        # Test decryption
        decrypted = cipher.decrypt(nonce, ciphertext_with_tag, aad)
        assert decrypted == plaintext, "Decryption mismatch"

    def test_aead_decryption_appendix_a5(self) -> None:
        """RFC 8439 Appendix A.5 - ChaCha20-Poly1305 AEAD Decryption."""
        key = bytes.fromhex("1c9240a5eb55d38af333888604f6b5f0473917c1402b80099dca5cbc207075c0")
        nonce = bytes.fromhex("000000000102030405060708")
        aad = bytes.fromhex("f33388860000000000004e91")

        # Ciphertext from RFC 8439 Appendix A.5 (265 bytes)
        ciphertext = bytes.fromhex(
            "64a0861575861af460f062c79be643bd"
            "5e805cfd345cf389f108670ac76c8cb2"
            "4c6cfc18755d43eea09ee94e382d26b0"
            "bdb7b73c321b0100d4f03b7f355894cf"
            "332f830e710b97ce98c8a84abd0b9481"
            "14ad176e008d33bd60f982b1ff37c855"
            "9797a06ef4f0ef61c186324e2b350638"
            "3606907b6a7c02b0f9f6157b53c867e4"
            "b9166c767b804d46a59b5216cde7a4e9"
            "9040c5a40433225ee282a1b0a06c523e"
            "af4534d7f83fa1155b0047718cbc546a"
            "0d072b04b3564eea1b422273f548271a"
            "0bb2316053fa76991955ebd63159434e"
            "cebb4e466dae5a1073a6727627097a10"
            "49e617d91d361094fa68f0ff77987130"
            "305beaba2eda04df997b714d6c6f2c29"
            "a6ad5cb4022b02709b"
        )
        tag = bytes.fromhex("eead9d67890cbb22392336fea1851f38")

        expected_plaintext = bytes.fromhex(
            "496e7465726e65742d44726166747320"
            "61726520647261667420646f63756d65"
            "6e74732076616c696420666f72206120"
            "6d6178696d756d206f6620736978206d"
            "6f6e74687320616e64206d6179206265"
            "20757064617465642c207265706c6163"
            "65642c206f72206f62736f6c65746564"
            "206279206f7468657220646f63756d65"
            "6e747320617420616e792074696d652e"
            "20497420697320696e617070726f7072"
            "6961746520746f2075736520496e7465"
            "726e65742d4472616674732061732072"
            "65666572656e6365206d617465726961"
            "6c206f7220746f206369746520746865"
            "6d206f74686572207468616e20617320"
            "2fe2809c776f726b20696e2070726f67"
            "726573732e2fe2809d"
        )

        cipher = ChaCha20Poly1305(key)
        ciphertext_with_tag = ciphertext + tag

        # Test decryption
        plaintext = cipher.decrypt(nonce, ciphertext_with_tag, aad)
        assert plaintext == expected_plaintext, "Decryption mismatch in A.5"

    def test_poly1305_key_generation_a4(self) -> None:
        """RFC 8439 Appendix A.4 - Poly1305 Key Generation Using ChaCha20.

        This tests that the key generation for Poly1305 from ChaCha20 works correctly.
        The one-time key is generated by running ChaCha20 with counter=0 and taking
        the first 32 bytes.
        """
        key = bytes.fromhex("808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f")
        nonce = bytes.fromhex("000000000001020304050607")

        # Expected one-time Poly1305 key (first 32 bytes of ChaCha20 output)
        # From RFC 8439 A.4: 8ad5a08b905f81cc815040274ab29471a833b637e3fd0da508dbb8e2fdd1a646
        # We can verify this indirectly by encrypting empty data
        # The tag will be computed using this key
        # For now, we just verify the AEAD works with this key/nonce
        cipher = ChaCha20Poly1305(key)

        # Encrypt empty message
        ciphertext = cipher.encrypt(nonce, b"", b"")
        # Should be just the 16-byte tag
        assert len(ciphertext) == 16, "Empty encryption should produce only tag"

    def test_sunscreen_message(self) -> None:
        """Test the famous 'sunscreen' message from Section 2.8.2."""
        key = bytes.fromhex("808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f")
        nonce = bytes.fromhex("070000004041424344454647")
        aad = bytes.fromhex("50515253c0c1c2c3c4c5c6c7")

        # The famous plaintext
        plaintext = (
            b"Ladies and Gentlemen of the class of '99: "
            b"If I could offer you only one tip for the future, sunscreen would be it."
        )

        cipher = ChaCha20Poly1305(key)

        # Encrypt
        ciphertext = cipher.encrypt(nonce, plaintext, aad)

        # Decrypt and verify roundtrip
        decrypted = cipher.decrypt(nonce, ciphertext, aad)
        assert decrypted == plaintext, "Roundtrip failed"

        # Verify ciphertext length (plaintext + 16-byte tag)
        assert len(ciphertext) == len(plaintext) + 16, "Wrong ciphertext length"
