class NativeError(Exception): ...

def native_build_info() -> tuple[str, str, int]: ...
def native_generate_key_pair() -> tuple[bytes, bytes]: ...

class Client:
    def __init__(
        self,
        recipient_public_key: bytes,
        recipient_key_id: bytes,
        psk: bytes,
        psk_id: bytes,
        limits: tuple[int | None, int | None, int | None, int | None],
        compression: str | None = None,
    ) -> None: ...
    def protect(
        self,
        method: str,
        authority: bytes,
        path: bytes,
        headers: list[tuple[str, str]],
        body: bytes,
    ) -> ProtectedRequest: ...

class ProtectedRequest:
    def take_envelope(self) -> bytes: ...
    @property
    def consumed(self) -> bool: ...
    def open_response(self, envelope: bytes) -> tuple[int, list[tuple[str, str]], bytes]: ...
    def discard(self) -> None: ...

class Server:
    def __init__(
        self,
        recipient_private_key: bytes,
        recipient_key_id: bytes,
        limits: tuple[int | None, int | None, int | None, int | None],
        compression: bool = False,
    ) -> None: ...
    def preparse(self, envelope: bytes) -> PreparsedRequest: ...

class PreparsedRequest:
    @property
    def psk_id(self) -> bytes: ...
    @property
    def consumed(self) -> bool: ...
    def authenticate(self, server: Server, psk: bytes) -> AuthenticatedRequest: ...
    def discard(self) -> None: ...

class AuthenticatedRequest:
    @property
    def replay_id(self) -> bytes: ...
    @property
    def retain_until_exclusive(self) -> int: ...
    @property
    def consumed(self) -> bool: ...
    def admit(self, admitted: bool) -> OpenedRequest: ...
    def discard(self) -> None: ...

class OpenedRequest:
    @property
    def method(self) -> str: ...
    @property
    def authority(self) -> bytes: ...
    @property
    def path(self) -> bytes: ...
    @property
    def headers(self) -> list[tuple[str, str]]: ...
    def take_body(self) -> bytes: ...
    @property
    def response_consumed(self) -> bool: ...
    def protect_response(
        self,
        status: int,
        headers: list[tuple[str, str]],
        body: bytes,
    ) -> bytes: ...
    def discard_response(self) -> None: ...
